version: '3'

services:

  R1:
    image: frr:3.0.2
    hostname: R1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

  R2:
    image: frr:3.0.2
    hostname: R2
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

  R3:
    image: frr:3.0.2
    hostname: R3
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

