version: '3'

services:

  C1:
    image: paultiplady/netperf
    hostname: C1

  C2:
    image: paultiplady/netperf
    hostname: C1

  C3:
    image: paultiplady/netperf
    hostname: C1

  R1:
    image: frr:3.0.2
    hostname: R1
    restart: always
    privileged: true
    volumes:
      - ./R1/frr:/etc/frr
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

  R2:
    image: frr:3.0.2
    hostname: R2
    restart: always
    privileged: true
    volumes:
      - ./R2/frr:/etc/frr
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

  R3:
    image: frr:3.0.2
    hostname: R3
    restart: always
    privileged: true
    volumes:
      - ./R3/frr:/etc/frr
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.mpls.platform_labels: 100000
      net.mpls.conf.eth0.input: 1

